### ISSUE TITLE
Multiple commands produce Parse.bundle

### ISSUE THREAD

**Issue by Kiplol** [parse-community/Parse-SDK-iOS-OSX#1505]
Xcode 11.4
Default build system

When trying to archive app using Parse and Parse/FacebookUtils integrated via Cocoapods, I get this build error.

```
Multiple commands produce '<removed>/UninstalledProducts/iphoneos/Parse.bundle':
1) Target 'Parse-Parse' has create directory command with output '<removed>/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Parse.bundle'
2) Target 'Parse.default-FacebookUtils-Parse' has create directory command with output '<removed>/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Parse.bundle'
```
 Parse and Parse/FacebookUtils are version 1.18.0.

**Comment by noobs2ninjas** [comment]
Interesting. I'll take a look.

**Comment by Kiplol** [comment]
I've been able to work around this by following these steps while arciving.

1. Rename the product name from Parse to anything else in Pods project Parse.default-FacebookUtils-Parse target
2. Change Parse.bundle to that new name in AppName project's AppName target's [CP] Copy Pods Resources Input Files
3. Delete ALL Output files right below
4. Change "Parse.bundle" in Pods/Target Support Files/Pods-AppName/Pods-AppName-resources.sh to the new name.

**Comment by bcbeta** [comment]
With Xcode 12 beta I am getting "multiple commands produce" errors for bolts and FacebookUtils.
<img width="907" alt="Screen Shot 2020-07-31 at 12 08 25 AM" src="https://user-images.githubusercontent.com/1378780/89005667-461cc380-d2c2-11ea-85fb-b69f11868e46.png">

**Comment by bcbeta** [comment]
@Kiplol could you explain how you fixed this error? I get warnings in the simulator but error when trying to archive. Any help would be appreciated. thanks!

**Comment by bcbeta** [comment]
Removing use_frameworks! from the Podfile and then changing the product name as you suggested allowed me to build.

**Comment by drdaz** [comment]
Can you confirm whether you still need to take these steps using the current code on master?

**Comment by bcbeta** [comment]
Yes, this was happening with the master as of two days ago.

**Comment by drdaz** [comment]
@bcbeta I merged a couple of PRs to master yesterday. I did some work with these build ambiguities in there, so I'd be interested to hear if it's still the case 🙂

**Comment by nebitrams** [comment]
I see this error only during Archiving.

```
Multiple commands produce '/Users/me/Library/Developer/Xcode/DerivedData/MyApp-gzgwdoovsnudgranphnqjcrcijbi/Build/Intermediates.noindex/ArchiveIntermediates/My App/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Parse.framework':
1) Target 'Parse' has create directory command with output '/Users/me/Library/Developer/Xcode/DerivedData/MyApp-gzgwdoovsnudgranphnqjcrcijbi/Build/Intermediates.noindex/ArchiveIntermediates/My App/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Parse.framework'
2) Target 'Parse.default-UI' has create directory command with output '/Users/me/Library/Developer/Xcode/DerivedData/MyApp-gzgwdoovsnudgranphnqjcrcijbi/Build/Intermediates.noindex/ArchiveIntermediates/My App/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Parse.framework'

```

Using using Xcode 11.5 and pod file as follows

```
platform :ios, '9.0'
use_frameworks!

target 'My App' do
  pod 'Parse', '1.18.0'
  pod 'Parse/UI', '1.18.0'
end
```

**Comment by bcbeta** [comment]
I am still getting the multiple commands error with the most recent master.

<img width="717" alt="Screen Shot 2020-08-14 at 9 14 56 PM" src="https://user-images.githubusercontent.com/1378780/90304304-8e67e400-de73-11ea-9e8a-4428fd5c71c8.png">

I am confused because the error is occurring in the widget extension target, but this target does not use the facebookutils framework. Podfile is below-
`
platform :ios, '12.0'
use_modular_headers!

def parse_utilities
    pod 'Parse/UI', :git => 'https://github.com/parse-community/Parse-SDK-iOS-OSX.git', :branch => 'master'
    pod 'Parse/FacebookUtils', :git => 'https://github.com/parse-community/Parse-SDK-iOS-OSX.git', :branch => 'master'
end

def parse_framework
    pod 'Parse', :git => 'https://github.com/parse-community/Parse-SDK-iOS-OSX.git', :branch => 'master'
end

target 'BackcountrySkiTracker' do
    parse_framework
    parse_utilities
    pod 'INTULocationManager'
    pod 'DKImagePickerController'
    pod 'UIImageView-Letters'
end


target 'BCWeatherWidgetExtension' do
    parse_framework

end`

**Comment by nebitrams** [comment]
> I am still getting the multiple commands error with the most recent master.
> 
> <img alt="Screen Shot 2020-08-14 at 9 14 56 PM" width="717" src="https://user-images.githubusercontent.com/1378780/90304304-8e67e400-de73-11ea-9e8a-4428fd5c71c8.png">
> 
> I am confused because the error is occurring in the widget extension target, but this target does not use the facebookutils framework. Podfile is below-
> `
> platform :ios, '12.0'
> use_modular_headers!
> 
> def parse_utilities
> pod 'Parse/UI', :git => 'https://github.com/parse-community/Parse-SDK-iOS-OSX.git', :branch => 'master'
> pod 'Parse/FacebookUtils', :git => 'https://github.com/parse-community/Parse-SDK-iOS-OSX.git', :branch => 'master'
> end
> 
> def parse_framework
> pod 'Parse', :git => 'https://github.com/parse-community/Parse-SDK-iOS-OSX.git', :branch => 'master'
> end
> 
> target 'BackcountrySkiTracker' do
> parse_framework
> parse_utilities
> pod 'INTULocationManager'
> pod 'DKImagePickerController'
> pod 'UIImageView-Letters'
> end
> 
> target 'BCWeatherWidgetExtension' do
> parse_framework
> 
> end`

Could you try this and see if it works?

`
platform :ios, '12.0'
use_modular_headers!

def parse_utilities
pod 'Parse/UI', :git => 'https://github.com/parse-community/Parse-SDK-iOS-OSX.git', :branch => 'master'
pod 'Parse/FacebookUtils', :git => 'https://github.com/parse-community/Parse-SDK-iOS-OSX.git', :branch => 'master'
pod 'Parse', :git => 'https://github.com/parse-community/Parse-SDK-iOS-OSX.git', :branch => 'master'
end

target 'BackcountrySkiTracker' do
parse_utilities
pod 'INTULocationManager'
pod 'DKImagePickerController'
pod 'UIImageView-Letters'
end

target 'BCWeatherWidgetExtension' do
parse_utilities
`

**Comment by bcbeta** [comment]
I can't install the FBSDK in the extension because sharedApplication is not available for that target-

<img width="634" alt="Screen Shot 2020-08-15 at 11 39 52 AM" src="https://user-images.githubusercontent.com/1378780/90318195-17bafd00-deec-11ea-8d76-72069d67ebc7.png">

**Comment by Kiplol** [comment]
> I see this error only during Archiving. Is anyone also facing this issue?

Mine is present only during archiving as well.

**Comment by benpackard** [comment]
Is it possible this issue is related to https://github.com/CocoaPods/CocoaPods/issues/8206?

**Comment by Kiplol** [comment]
@benpackard , yes, I have multiple targets, extensions, and use the Parse/FacebookUtils subspec.

**Comment by benpackard** [comment]
Anyone have any thoughts on what is required to fix this? Or even what kind of expertise is needed? As I understand it, it is currently not possible to archive an app that uses Parse and has any other target, such as a Widget. 

I think we can be slightly narrower though - a project that only uses the Parse SDK itself archives ok. It's the use of any submodule that causes issues.

For example, this will archive:

```
use_frameworks!
inhibit_all_warnings!

target "ParseWidgetTest" do
	platform :ios, '11.0'
	pod 'Parse', '1.19.0'
end

target "CoolWidgetExtension" do
	platform :ios, '11.0'
	pod 'Parse', '1.19.0'
end

```

But this will not:

```
use_frameworks!
inhibit_all_warnings!

target "ParseWidgetTest" do
	platform :ios, '11.0'
	pod 'Parse', '1.19.0'
	pod 'Parse/UI', '1.19.0'  # <-----
end

target "CoolWidgetExtension" do
	platform :ios, '11.0'
	pod 'Parse', '1.19.0'
end
```

The errors are the same as those reported earlier.

**Comment by bcbeta** [comment]
I was able to get my project to archive using these instructions https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1505#issuecomment-632820475, but I do not know enough about cocoapods or frameworks to come up with a more permanent fix.

**Comment by benpackard** [comment]
I wonder if this is a cocoapods issue or something on our Parse pod side. Most of the fixes for this issue for other projects don't work here, and we have to resort to the fix mentioned by @bcbeta. Maybe someone with more knowledge will be able to help.

**Comment by Kiplol** [comment]
While #1505 (comment)

**Comment by Kiplol** [comment]
While [this workaround](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1505#issuecomment-632820475) still works for me, it removes the ability to use use_frameworks!.  Has anyone figured out a different workaround?

**Comment by Kiplol** [comment]
Hi, I'm still having this issue on Xcode 12.5, cocoa pods 1.10.1, Parse/Core and Parse/FacebookUtils 1.19.2.

`error: Multiple commands produce '/Users/runner/Library/Developer/Xcode/DerivedData/scy-cifziqnafebkbeeykfagqbprxptp/Build/Intermediates.noindex/ArchiveIntermediates/scy/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Parse.bundle':
1) Target 'Parse-Core-FacebookUtils-Parse' has create directory command with output '/Users/runner/Library/Developer/Xcode/DerivedData/scy-cifziqnafebkbeeykfagqbprxptp/Build/Intermediates.noindex/ArchiveIntermediates/scy/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Parse.bundle'
2) Target 'Parse-Core-Parse' has create directory command with output '/Users/runner/Library/Developer/Xcode/DerivedData/scy-cifziqnafebkbeeykfagqbprxptp/Build/Intermediates.noindex/ArchiveIntermediates/scy/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Parse.bundle'`

**Comment by benpackard** [comment]
Same here. I've found that I can delete derived data, clean the project and 50% of the time it builds. I have to repeat it until it works. Very strange.

**Comment by benpackard** [comment]
Just a note to confirm that this is still an issue using Xcode 13.3.1, cocoapods 1.11.2, and Parse SDK 1.19.3

**Comment by dplewis** [comment]
Closing as we have moved from Pods to SPM
